# Generated by Django 5.1.7 on 2025-03-18 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outflow',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='outflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
